# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/zen/Google Drive/Spring 2017/CIS 099/Harris3DSrouce"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/zen/Google Drive/Spring 2017/CIS 099/Harris3DSrouce"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/zen/Google Drive/Spring 2017/CIS 099/Harris3DSrouce/CMakeFiles" "/Users/zen/Google Drive/Spring 2017/CIS 099/Harris3DSrouce/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/zen/Google Drive/Spring 2017/CIS 099/Harris3DSrouce/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named Harris3DSrouce

# Build rule for target.
Harris3DSrouce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Harris3DSrouce
.PHONY : Harris3DSrouce

# fast build rule for target.
Harris3DSrouce/fast:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/build
.PHONY : Harris3DSrouce/fast

#=============================================================================
# Target rules for targets named Vertex

# Build rule for target.
Vertex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Vertex
.PHONY : Vertex

# fast build rule for target.
Vertex/fast:
	$(MAKE) -f CMakeFiles/Vertex.dir/build.make CMakeFiles/Vertex.dir/build
.PHONY : Vertex/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named Properties

# Build rule for target.
Properties: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Properties
.PHONY : Properties

# fast build rule for target.
Properties/fast:
	$(MAKE) -f CMakeFiles/Properties.dir/build.make CMakeFiles/Properties.dir/build
.PHONY : Properties/fast

#=============================================================================
# Target rules for targets named Mesh

# Build rule for target.
Mesh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Mesh
.PHONY : Mesh

# fast build rule for target.
Mesh/fast:
	$(MAKE) -f CMakeFiles/Mesh.dir/build.make CMakeFiles/Mesh.dir/build
.PHONY : Mesh/fast

#=============================================================================
# Target rules for targets named HarrisDetector

# Build rule for target.
HarrisDetector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HarrisDetector
.PHONY : HarrisDetector

# fast build rule for target.
HarrisDetector/fast:
	$(MAKE) -f CMakeFiles/HarrisDetector.dir/build.make CMakeFiles/HarrisDetector.dir/build
.PHONY : HarrisDetector/fast

HarrisDetector.o: HarrisDetector.cpp.o

.PHONY : HarrisDetector.o

# target to build an object file
HarrisDetector.cpp.o:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/HarrisDetector.cpp.o
	$(MAKE) -f CMakeFiles/HarrisDetector.dir/build.make CMakeFiles/HarrisDetector.dir/HarrisDetector.cpp.o
.PHONY : HarrisDetector.cpp.o

HarrisDetector.i: HarrisDetector.cpp.i

.PHONY : HarrisDetector.i

# target to preprocess a source file
HarrisDetector.cpp.i:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/HarrisDetector.cpp.i
	$(MAKE) -f CMakeFiles/HarrisDetector.dir/build.make CMakeFiles/HarrisDetector.dir/HarrisDetector.cpp.i
.PHONY : HarrisDetector.cpp.i

HarrisDetector.s: HarrisDetector.cpp.s

.PHONY : HarrisDetector.s

# target to generate assembly for a file
HarrisDetector.cpp.s:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/HarrisDetector.cpp.s
	$(MAKE) -f CMakeFiles/HarrisDetector.dir/build.make CMakeFiles/HarrisDetector.dir/HarrisDetector.cpp.s
.PHONY : HarrisDetector.cpp.s

Mesh.o: Mesh.cpp.o

.PHONY : Mesh.o

# target to build an object file
Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/Mesh.cpp.o
	$(MAKE) -f CMakeFiles/Mesh.dir/build.make CMakeFiles/Mesh.dir/Mesh.cpp.o
.PHONY : Mesh.cpp.o

Mesh.i: Mesh.cpp.i

.PHONY : Mesh.i

# target to preprocess a source file
Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/Mesh.cpp.i
	$(MAKE) -f CMakeFiles/Mesh.dir/build.make CMakeFiles/Mesh.dir/Mesh.cpp.i
.PHONY : Mesh.cpp.i

Mesh.s: Mesh.cpp.s

.PHONY : Mesh.s

# target to generate assembly for a file
Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/Mesh.cpp.s
	$(MAKE) -f CMakeFiles/Mesh.dir/build.make CMakeFiles/Mesh.dir/Mesh.cpp.s
.PHONY : Mesh.cpp.s

Properties.o: Properties.cpp.o

.PHONY : Properties.o

# target to build an object file
Properties.cpp.o:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/Properties.cpp.o
	$(MAKE) -f CMakeFiles/Properties.dir/build.make CMakeFiles/Properties.dir/Properties.cpp.o
.PHONY : Properties.cpp.o

Properties.i: Properties.cpp.i

.PHONY : Properties.i

# target to preprocess a source file
Properties.cpp.i:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/Properties.cpp.i
	$(MAKE) -f CMakeFiles/Properties.dir/build.make CMakeFiles/Properties.dir/Properties.cpp.i
.PHONY : Properties.cpp.i

Properties.s: Properties.cpp.s

.PHONY : Properties.s

# target to generate assembly for a file
Properties.cpp.s:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/Properties.cpp.s
	$(MAKE) -f CMakeFiles/Properties.dir/build.make CMakeFiles/Properties.dir/Properties.cpp.s
.PHONY : Properties.cpp.s

Vertex.o: Vertex.cpp.o

.PHONY : Vertex.o

# target to build an object file
Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/Vertex.cpp.o
	$(MAKE) -f CMakeFiles/Vertex.dir/build.make CMakeFiles/Vertex.dir/Vertex.cpp.o
.PHONY : Vertex.cpp.o

Vertex.i: Vertex.cpp.i

.PHONY : Vertex.i

# target to preprocess a source file
Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/Vertex.cpp.i
	$(MAKE) -f CMakeFiles/Vertex.dir/build.make CMakeFiles/Vertex.dir/Vertex.cpp.i
.PHONY : Vertex.cpp.i

Vertex.s: Vertex.cpp.s

.PHONY : Vertex.s

# target to generate assembly for a file
Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/Vertex.cpp.s
	$(MAKE) -f CMakeFiles/Vertex.dir/build.make CMakeFiles/Vertex.dir/Vertex.cpp.s
.PHONY : Vertex.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

util.o: util.cpp.o

.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/util.cpp.o
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i

.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/util.cpp.i
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s

.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/util.cpp.s
	$(MAKE) -f CMakeFiles/Harris3DSrouce.dir/build.make CMakeFiles/Harris3DSrouce.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... util"
	@echo "... Harris3DSrouce"
	@echo "... Vertex"
	@echo "... main"
	@echo "... Properties"
	@echo "... rebuild_cache"
	@echo "... Mesh"
	@echo "... HarrisDetector"
	@echo "... HarrisDetector.o"
	@echo "... HarrisDetector.i"
	@echo "... HarrisDetector.s"
	@echo "... Mesh.o"
	@echo "... Mesh.i"
	@echo "... Mesh.s"
	@echo "... Properties.o"
	@echo "... Properties.i"
	@echo "... Properties.s"
	@echo "... Vertex.o"
	@echo "... Vertex.i"
	@echo "... Vertex.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

